
productos_disponibles  = [
    {'Marca': "Samsung", 'NombreProducto': "Samsung Galaxy A34 128 Gb", 'PrecioProducto': 8000.00},
    {'Marca': "LG", 'NombreProducto': "Pantalla LED 32 in. FULL HD", 'PrecioProducto': 3999.00},
    {'Marca': "Vento", 'NombreProducto': "Motocicleta Crossmax Pro cc 2024", 'PrecioProducto': 41999.00},
    {'Marca': "Hisense", 'NombreProducto': "Pantalla LED 55 in. UHD 4K", 'PrecioProducto': 7999.00},
    {'Marca': "HP", 'NombreProducto': "Laptop 14 in. Intel Core i3 8 gb RAM", 'PrecioProducto': 8799.00},
    {'Marca': "Nike", 'NombreProducto': "Tenis Nike Renew Ride 2", 'PrecioProducto': 1099.00},
    {'Marca': "Puma", 'NombreProducto': "Tenis Puma Softride Premier Slip On", 'PrecioProducto': 1299.00},
    {'Marca': "Nike", 'NombreProducto': "Tenis Nike Court Royale 2", 'PrecioProducto': 1699.00},
    {'Marca': "Sony", 'NombreProducto': "PlayStation 5 1Tb - Color blanco", 'PrecioProducto': 9699.00},
    {'Marca': "Nintendo", 'NombreProducto': "Nintendo Switch Oled 64 Gb Oled", 'PrecioProducto': 4999.00},
    {'Marca': "Microsoft", 'NombreProducto': "Consola Xbox Series s de 1 TB", 'PrecioProducto': 8399.00},
    {'Marca': "Whrilpool", 'NombreProducto': "Lavadora Whirlpool Automatica", 'PrecioProducto': 13999.00},
    {'Marca': "Panasonic", 'NombreProducto': "Horno de Microondas Panasonic 1.3 pies NN-", 'PrecioProducto': 1999.00},
    {'Marca': "Adidas", 'NombreProducto': "Pants Adidas color Negro", 'PrecioProducto': 649.00},
    {'Marca': "Adidas", 'NombreProducto': "Tenis Adidas Streetcheck para Hombre", 'PrecioProducto': 1699.00},
    {'Marca': "Lego", 'NombreProducto': "Lego Minecraft: La mina Abandonada", 'PrecioProducto': 519.00},
    {'Marca': "Blender", 'NombreProducto': "Licuadora Personal Blender 2 Go!", 'PrecioProducto': 169.99},
    {'Marca': "Rca", 'NombreProducto': "Bocina Bluetooth RCA 50 W", 'PrecioProducto': 599.00},
    {'Marca': "Record", 'NombreProducto': "Ventilador de Mesa Record 12 in.", 'PrecioProducto': 799.00},
    {'Marca': "Hasbro", 'NombreProducto': "Spider-Rex Marvel con Sonido", 'PrecioProducto': 970.00},
    {'Marca': "Hot-Wheels", 'NombreProducto': "Pista Hot Wheels Rainbows Road", 'PrecioProducto': 3799.00},
    {'Marca': "Fisher Price", 'NombreProducto': "Pila de Aritos Eco Fisher Price", 'PrecioProducto': 99.99},
    {'Marca': "Apple", 'NombreProducto': "Iphone 13 128Gb Azul", 'PrecioProducto': 18999.00},
    {'Marca': "Apple", 'NombreProducto': "Iphone 12 256 Gb Blanco", 'PrecioProducto': 12999.00},
    {'Marca': "Motorola", 'NombreProducto': "Celular Motorola G23", 'PrecioProducto': 4499.99},
    {'Marca': "Xiaomi", 'NombreProducto': "Celular Xiaomi Redmi Note 12 pro 256 GB", 'PrecioProducto': 4747.00},
    {'Marca': "Samsung", 'NombreProducto': "Samsung Galaxy A54 256 Gb", 'PrecioProducto': 9999.00},
    {'Marca': "Zuum", 'NombreProducto': "Celular Zuum Akus P1 32 Gb", 'PrecioProducto': 1799.99},
    {'Marca': "Spring Air", 'NombreProducto': "Colchon King Size Spring Air", 'PrecioProducto': 7499.99},
    {'Marca': "MonteVideo", 'NombreProducto': "Sofa Montevideo Contemporaneo color Cafe", 'PrecioProducto': 6999.00}
]
